# Generated by Django 3.0.1 on 2019-12-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_Usage', models.CharField(max_length=10000)),
                ('actual_Usage', models.CharField(max_length=10000)),
                ('difference', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'tower_model',
            },
        ),
    ]
